server:
  port: 9999

spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql:///test
  redis:
    port: 6379
    host: localhost

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  level:
    com.lvfei: debug

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1

